# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'workRavenUser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for workRavenUser
  rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'
  
    # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'CxxBridge',
      'RCTLinkingIOS',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTCameraRoll',
      'RCTVibration',
      'RCTWebSocket',
      'ART'
    ]
  
    # React Native third party dependencies podspecs
    pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
    
    pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
    # If you are using React Native <0.54, you will get the following error:
    # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
    # Use the following line instead:
    #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
    pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  

  pod 'Paystack'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Functions', '~> 5.20.1'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
 
  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  target 'workRavenUserTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


target 'workRavenUser-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for workRavenUser-tvOS

  target 'workRavenUser-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
